spring:
  datasource:
    url: jdbc:mysql://root:eJsIuxHMVjGzjC8wjSGn@containers-us-west-176.railway.app:7538/railway
    username: root
    password: eJsIuxHMVjGzjC8wjSGn

feign:
  client:
    config:
      default:
        connectTimeout: 30000
        readTimeout: 30000
        decode404: true